namespace MedFlow.Infrastructure.Persistence;

/// <summary>
/// DDL por provider. Sao scripts curtos e idempotentes; nao usamos migrations do
/// EF Core porque a maior parte da persistencia e Dapper - manter as duas fontes de
/// verdade sincronizadas seria pior do que ter o DDL explicito num lugar so.
/// </summary>
internal static class SchemaScripts
{
    public static string Para(string provider) =>
        provider is "postgres" or "postgresql" ? Postgres : Sqlite;

    private const string Postgres = """
        CREATE TABLE IF NOT EXISTS convenio (
            id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            nome  VARCHAR(120) NOT NULL UNIQUE,
            ativo BOOLEAN      NOT NULL DEFAULT TRUE
        );
        CREATE TABLE IF NOT EXISTS paciente (
            id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            nome            VARCHAR(150) NOT NULL,
            cpf             VARCHAR(14)  NOT NULL UNIQUE,
            data_nascimento DATE         NOT NULL,
            email           VARCHAR(150),
            telefone        VARCHAR(20),
            convenio_id     BIGINT
        );
        CREATE TABLE IF NOT EXISTS profissional (
            id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            nome          VARCHAR(150) NOT NULL,
            especialidade VARCHAR(80)  NOT NULL,
            crm           VARCHAR(20)  NOT NULL UNIQUE,
            ativo         BOOLEAN      NOT NULL DEFAULT TRUE
        );
        CREATE TABLE IF NOT EXISTS consulta (
            id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            paciente_id        BIGINT      NOT NULL,
            profissional_id    BIGINT      NOT NULL,
            data_hora          TIMESTAMP   NOT NULL,
            status             VARCHAR(40) NOT NULL,
            procedimento       VARCHAR(120) NOT NULL,
            cobertura_convenio VARCHAR(40),
            criado_em          TIMESTAMP   NOT NULL
        );
        CREATE INDEX IF NOT EXISTS idx_consulta_profissional_data ON consulta (profissional_id, data_hora);
        CREATE TABLE IF NOT EXISTS registro_clinico (
            id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            consulta_id     BIGINT       NOT NULL,
            paciente_id     BIGINT       NOT NULL,
            profissional_id BIGINT       NOT NULL,
            diagnostico     VARCHAR(500) NOT NULL,
            prescricao      VARCHAR(1000),
            data_registro   TIMESTAMP    NOT NULL
        );
        CREATE INDEX IF NOT EXISTS idx_registro_paciente ON registro_clinico (paciente_id, data_registro);
        """;

    private const string Sqlite = """
        CREATE TABLE IF NOT EXISTS convenio (
            id    INTEGER PRIMARY KEY AUTOINCREMENT,
            nome  TEXT    NOT NULL UNIQUE,
            ativo INTEGER NOT NULL DEFAULT 1
        );
        CREATE TABLE IF NOT EXISTS paciente (
            id              INTEGER PRIMARY KEY AUTOINCREMENT,
            nome            TEXT    NOT NULL,
            cpf             TEXT    NOT NULL UNIQUE,
            data_nascimento TEXT    NOT NULL,
            email           TEXT,
            telefone        TEXT,
            convenio_id     INTEGER
        );
        CREATE TABLE IF NOT EXISTS profissional (
            id            INTEGER PRIMARY KEY AUTOINCREMENT,
            nome          TEXT    NOT NULL,
            especialidade TEXT    NOT NULL,
            crm           TEXT    NOT NULL UNIQUE,
            ativo         INTEGER NOT NULL DEFAULT 1
        );
        CREATE TABLE IF NOT EXISTS consulta (
            id                 INTEGER PRIMARY KEY AUTOINCREMENT,
            paciente_id        INTEGER NOT NULL,
            profissional_id    INTEGER NOT NULL,
            data_hora          TEXT    NOT NULL,
            status             TEXT    NOT NULL,
            procedimento       TEXT    NOT NULL,
            cobertura_convenio TEXT,
            criado_em          TEXT    NOT NULL
        );
        CREATE INDEX IF NOT EXISTS idx_consulta_profissional_data ON consulta (profissional_id, data_hora);
        CREATE TABLE IF NOT EXISTS registro_clinico (
            id              INTEGER PRIMARY KEY AUTOINCREMENT,
            consulta_id     INTEGER NOT NULL,
            paciente_id     INTEGER NOT NULL,
            profissional_id INTEGER NOT NULL,
            diagnostico     TEXT    NOT NULL,
            prescricao      TEXT,
            data_registro   TEXT    NOT NULL
        );
        CREATE INDEX IF NOT EXISTS idx_registro_paciente ON registro_clinico (paciente_id, data_registro);
        """;

    /// <summary>
    /// Seed idempotente: roda em todo startup sem violar as constraints UNIQUE.
    /// A sintaxe INSERT ... SELECT ... WHERE NOT EXISTS funciona em ambos os bancos.
    /// Booleanos exigem o literal TRUE: o PostgreSQL nao faz coercao implicita de
    /// integer para boolean (SQLSTATE 42804), e o SQLite reconhece TRUE desde a 3.23.
    /// </summary>
    public const string Seed = """
        INSERT INTO convenio (nome, ativo)
        SELECT 'Unimed', TRUE WHERE NOT EXISTS (SELECT 1 FROM convenio WHERE nome = 'Unimed');

        INSERT INTO convenio (nome, ativo)
        SELECT 'Bradesco Saude', TRUE WHERE NOT EXISTS (SELECT 1 FROM convenio WHERE nome = 'Bradesco Saude');

        INSERT INTO profissional (nome, especialidade, crm, ativo)
        SELECT 'Dra. Helena Prado', 'CARDIOLOGIA', 'CRM-SP-112233', TRUE
        WHERE NOT EXISTS (SELECT 1 FROM profissional WHERE crm = 'CRM-SP-112233');

        INSERT INTO profissional (nome, especialidade, crm, ativo)
        SELECT 'Dr. Rafael Nunes', 'ORTOPEDIA', 'CRM-SP-445566', TRUE
        WHERE NOT EXISTS (SELECT 1 FROM profissional WHERE crm = 'CRM-SP-445566');

        INSERT INTO paciente (nome, cpf, data_nascimento, email, telefone, convenio_id)
        SELECT 'Carlos Belchior', '111.222.333-44', '1990-05-14', 'carlos@exemplo.com', '17999990000', 1
        WHERE NOT EXISTS (SELECT 1 FROM paciente WHERE cpf = '111.222.333-44');

        INSERT INTO paciente (nome, cpf, data_nascimento, email, telefone, convenio_id)
        SELECT 'Marina Lopes', '555.666.777-88', '1985-11-02', 'marina@exemplo.com', '17988880000', 2
        WHERE NOT EXISTS (SELECT 1 FROM paciente WHERE cpf = '555.666.777-88');
        """;
}
